typography_spectrum: 0.27385
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.720387612702325
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: zgaglione
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Zachary Gaglione
description: Independant Web + Print Designer
purpose: []
