name: zgaglione
favicon: null
layout_spectrum: 0.49393
typography_spectrum: 0.75251
title: Zachary Gaglione
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.07783463876694441
  saturation: 0.11829800740815699
  rhythmicContrast: 0.720387612702325
purpose: []
